# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      metricRelabelings:
        - action: replace
          regex: (.*)
          replacement: kronos_$1
          sourceLabels:
          - __name__
          targetLabel: __name__
  selector:
    matchLabels:
      control-plane: controller-manager
