# permissions for end users to edit kronosapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kronosapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: Kronos-Core
    app.kubernetes.io/part-of: Kronos-Core
    app.kubernetes.io/managed-by: kustomize
  name: kronosapp-editor-role
rules:
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps/status
  verbs:
  - get
