# permissions for end users to view kronosapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kronosapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: Kronos-Core
    app.kubernetes.io/part-of: Kronos-Core
    app.kubernetes.io/managed-by: kustomize
  name: kronosapp-viewer-role
rules:
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps/status
  verbs:
  - get
