# permissions for end users to view kronosapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  name: kronosapp-viewer-role
rules:
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps/status
  verbs:
  - get
