---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps/finalizers
  verbs:
  - update
- apiGroups:
  - core.wecraft.tn
  resources:
  - kronosapps/status
  verbs:
  - get
  - patch
  - update
