apiVersion: core.wecraft.tn/v1alpha1
kind: KronosApp
metadata:
  labels:
  name: sleep-at-weekend
spec:
  startSleep: "18:00"
  endSleep: "20:41"
  weekdays: "1-5"
  timezone: "Africa/Tunis"
  includedObjects: 
    - apiVersion: "apps/v1"
      kind: "*"
      namespace: "default"
      includeRef: ""
      excludeRef: ""