//go:build !ignore_autogenerated

/*
Copyright 2024 IsmailAbdelkefi.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Holiday) DeepCopyInto(out *Holiday) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Holiday.
func (in *Holiday) DeepCopy() *Holiday {
	if in == nil {
		return nil
	}
	out := new(Holiday)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludedObject) DeepCopyInto(out *IncludedObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludedObject.
func (in *IncludedObject) DeepCopy() *IncludedObject {
	if in == nil {
		return nil
	}
	out := new(IncludedObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KronosApp) DeepCopyInto(out *KronosApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KronosApp.
func (in *KronosApp) DeepCopy() *KronosApp {
	if in == nil {
		return nil
	}
	out := new(KronosApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KronosApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KronosAppList) DeepCopyInto(out *KronosAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KronosApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KronosAppList.
func (in *KronosAppList) DeepCopy() *KronosAppList {
	if in == nil {
		return nil
	}
	out := new(KronosAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KronosAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KronosAppSpec) DeepCopyInto(out *KronosAppSpec) {
	*out = *in
	if in.Holidays != nil {
		in, out := &in.Holidays, &out.Holidays
		*out = make([]Holiday, len(*in))
		copy(*out, *in)
	}
	if in.IncludedObjects != nil {
		in, out := &in.IncludedObjects, &out.IncludedObjects
		*out = make([]IncludedObject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KronosAppSpec.
func (in *KronosAppSpec) DeepCopy() *KronosAppSpec {
	if in == nil {
		return nil
	}
	out := new(KronosAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KronosAppStatus) DeepCopyInto(out *KronosAppStatus) {
	*out = *in
	if in.CreatedSecrets != nil {
		in, out := &in.CreatedSecrets, &out.CreatedSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KronosAppStatus.
func (in *KronosAppStatus) DeepCopy() *KronosAppStatus {
	if in == nil {
		return nil
	}
	out := new(KronosAppStatus)
	in.DeepCopyInto(out)
	return out
}
